# Generated by Django 5.2.4 on 2026-07-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_shop_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='daily_revenue_goal',
            field=models.DecimalField(decimal_places=2, default=75000, max_digits=12),
        ),
    ]
