# Generated by Django 5.2.4 on 2026-07-18 10:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_shop_daily_revenue_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='shop_banner'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='shop_logo'),
        ),
    ]
